### ISSUE TITLE
Type definition of `. once(type, listener)` should have listener as optional parameter

### ISSUE THREAD

**Issue by abdatta** [yanickrochon/promise-events#22]
In the type definition, we see:
https://github.com/yanickrochon/promise-events/blob/b001fa29c32c887ebbef12e9e9e1b750185ffb79/emitter.d.ts#L21

It should be instead:
```ts
once(type: TEventType, listener?: TListener): Promise<any>;
```
since the listener parameter is optional as per documentation:

> emitter.once(eventName)
> 
> Returns a Promise that is resolved once only after all listeners for the specified event have been called for the given event. (Any newListener event will be emitted.)
> 

@yanickrochon  Let me know if you agree. I'll raise a PR for the same.

**Comment by yanickrochon** [comment]
Sounds about right! I do not use TS, personally, so all these PR are for the community :smile:

**Comment by abdatta** [comment]
Can you merge #23 then? Thank you 🙂

**Comment by yanickrochon** [comment]
Sorry, it's published!
