### ISSUE TITLE
Add prependListener() and prependOnceListener()

### ISSUE THREAD

**Issue by addaleax** [yanickrochon/promise-events#5]
I don’t know how interested you are in keeping this module up to date with Node.js’ own EventEmitter, but here’s a heads up: nodejs/node@0e7d57af3573b4dcba81217bba2f041dbdc173dc

**Comment by yanickrochon** [comment]
I haven't been following much of Node.js' dev recently, no. And, yes, this module is intended to be a drop-in replacement for the standard `EventEmitter`, so these methods should be implemented to be compliant. I'll see what I can do this weekend. 

Thanks for the heads up!

**Comment by yanickrochon** [comment]
This should do! Cheers!
