### ISSUE TITLE
Wouldn't Promise.each() make more sense than Promise.all() ?

### ISSUE THREAD

**Issue by cstavaru** [yanickrochon/promise-events#8]
Hello,

I found your library and it's excellent for my usage which relies heavily on events and promises. 

However, I think that using Promise.each() instead of Promise.all() for resolving chains of event handlers would be more in line with Node.js's Events module philosophy, which states: 

"The EventEmitter calls all listeners synchronously in the order in which they were registered. This is important to ensure the proper sequencing of events and to avoid race conditions or logic errors".

Actually, even in the case of using asynchronous handlers, the considerations above regarding ensuring proper event sequencing to avoid logic errors still apply. 

I think that providing an option on how the promise chains should be handled would be a great addition to the library.

Thanks !

**Comment by yanickrochon** [comment]
It is a valid point. I'll implement this and add a global setting so those who want `Promise.all` can still use it; the default will be a chained promise so the order of the event listeners are preserved.

**Comment by yanickrochon** [comment]
I have updated the dependencies and re-ran all tests. I did add the code to switch between sequential and concurrent execution of the handlers, however the tests did show no difference between `Promise.all` and chaining the handlers through a `Promise`. Still, I commented the old code and kept promise chaining as default.

If there is any problem with this change, please re-open the issue.

**Comment by cstavaru** [comment]
Seems to be working perfectly until now, thanks. And also thank you for some clean code related to dynamic promise chaining, pretty hard to find good examples.

**Comment by yanickrochon** [comment]
FYI : I did ask about Promise chaining [over six years ago](https://stackoverflow.com/questions/30823653/is-node-js-native-promise-all-processing-in-parallel-or-sequentially), and this is when I was taught about it. Also, I can't believe I wrote this module over 4 years ago already :smile:
